#! /bin/bash
if [ "$1" = '' ];
    then 
        echo -e '\e[31mPara crear un nuevo proyecto use:'
        echo './create el_nombre_proyecto'
        exit
fi
echo -e ''
read -p 'Descargar utilidades (enter) no, escriba algo y presione (enter) si: ' response
echo -e '\e[36m'
if [ "$response" != '' ];
    then
    ./update
fi
./clean
mkdir ../$1/
cp -r -f ./* ../$1/
echo -e '\n\e[32m[create]: Terminado :)\n\e[96m'
./open