#!/bin/bash
echo -e '\n\e[96m[open]: Abriendo carpeta de archivos'
nautilus . &
if [ `which texstudio` != '' ];
    then 
        echo '[open]: Abriendo TexStudio'
    texstudio --no-session ./report.tex ./pieces/header.tex ./referencias.bib &
fi
echo ''