#!/bin/bash
echo -e '[open]: Abriendo carpeta de archivos'
nautilus ../$1 &
if [ `which texstudio` != '' ];
    then 
        echo '[open]: Abriendo TexStudio'
    texstudio --no-session ../$1/report.tex ../$1/pieces/header.tex ../$1/referencias.bib &
fi
echo ''