#!/bin/bash
rm -r -f ./utilidades
sudo rm -r -f /usr/share/texlive/texmf-dist/tex/latex/utilidades
git clone https://github.com/BenyaminGaleano/utilidades.git
echo -e '\e[32m\n[update]: utilidades descargadas\e[39m'
echo ''
sudo mkdir /usr/share/texlive/texmf-dist/tex/latex/utilidades/
sudo mv ./utilidades/* /usr/share/texlive/texmf-dist/tex/latex/utilidades
rm -r -f ./utilidades
sudo mktexlsr /usr/share/texlive/texmf-dist/tex/latex/utilidades/
echo -e '\e[32m\n[update]: utilidades instaladas/actualizadas'
echo ''